### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dylanHco** [acarafat/tangler#1]
Hi Arafat,

Thanks for making such an easy program to use and understand! I do not have an issue using it, but more of a request/question. I was wondering if there was way to have the lines connect from the end of the tiplabel instead at the very tip of the branch. This way it would be easier to read the label names. In addition is there anyway to add tip labels to the other tree as well and just have the lines connect at the ends of the tip labels? 

Many thanks!
Dylan

**Comment by acarafat** [comment]
Hello Dylan,

Thank you so much for the suggestion! I'll add a feature for adjusting connect-line x-position soon to leave out the labels. 

Best,
Arafat

**Comment by acarafat** [comment]
Hello Dylan,

I have updated the code so that you can adjust the connecting lines' x-position. Now you can update the x-position of the lines' beginning and ending by **lab_pad**, which will introduce equidistant padding. 

Of course this is not the best solution, i.e. it assumes that the labels has similar length.  You can use the following solution for now:

```
# Update the connecting line x-position so that it do not overlap with tip-labels.
simple.tanglegram(tree1, tree2, Genotype, Green, tiplab = T, lab_pad = 3, x_hjust = 1)
```
Thanks for the suggestion! 

Best,
Arafat

**Comment by acarafat** [comment]
I'm reopening this issue, I'm not happy with the current solution!

**Comment by dylanHco** [comment]
Hi Arafat,

Thanks for updating the package with the label padding. I am still having some issues getting the names to display on both trees. I am using the ggtree to annotate tiplabel size on both trees:

tree1 <- ggtree(t1, branch.length = 'none')    %<+% meta + geom_tiplab(size = 2.4) + geom_tippoint(aes(color=Section)) 
tree2 <- ggtree(t2 , branch.length= 'none') %<+% meta + geom_tiplab(size = 2.4)

however when I run the tangler command with tiplab =F only tree 1 labels appear, and when i run tiplable =T, the second tree labels appear but in a much smaller font. Another thing I noticed is when I increase the lab_pad size the lines connecting tips gets shorter and when I try to adjust t2_pad to move closer, the connecting lines also get shorter. 

Thanks for working on this!

**Comment by acarafat** [comment]
I just pushed another quick update. So the `simple.tanglegram` function takes the following arguments now:

```
tree1 
tree2
column
value
t2_pad = 0.3
x_hjust = 1
lab_pad = 2
l_color = "grey"
tiplab = F
t2_y_pos = 0
t2_y_scale = 1
t2_branch_scale = 1
t2_tiplab_size = 1
t2_tiplab_pad = 0
```
Here, t2_tiplab_size has been introduced to control Tree 2 tip labels. Also, t2_pad updated to improve behaviour. 

I have a decent looking tanglegram with the following command:

```
tangler::simple.tanglegram(t1, t2, sample_type, clinical, t2_pad = 0.5,
                           tiplab = T, lab_pad = 0, x_hjust = 1, 
                           t2_y_pos = 0, t2_y_scale = 1.5, t2_branch_scale = 0.3)
``` 

Let me know if that works for you!

**Comment by dylanHco** [comment]
I think its looking really good! Thanks for adding that parameter. My last question would be do you have any suggestions to rotate nodes? There are some nodes/tips/clades that have the same relationship in both trees, but because they are not aligned the lines cross and give the appearance that maybe its not the same relationship on both trees. Here is an example attached - A.orientalis and A. elliptica are sister species but there lines cross. I have tried to ladderize the trees before using the function to plot. ANy thoughts? Thanks so much!  
<img width="577" alt="Screenshot 2024-07-09 at 10 48 56 AM" src="https://github.com/acarafat/tangler/assets/57578571/ab7825a8-46e7-41ee-bea8-f9004bca0303">

**Comment by acarafat** [comment]
You mean ordering the tip-labels? I think that's excellent suggestion and I have the same thing in the mind to for next update. I will get back to you soon!

**Comment by dylanHco** [comment]
Yes, just having the same order on each tree would make it a lot easier to read when you have large trees. Thanks!

**Comment by acarafat** [comment]
Hello @dylanHco ,

I have added functionality to rearrange/reorder the tips without changing phylogenetic topography. Please check v0.2.1!  

Sorry it took some time for me to get back!

Best, Arafat
